### ISSUE TITLE
Derived ShaderType rust-analyzer error

### ISSUE THREAD

**Issue by paulkre** [teoxoy/encase#34]
I'm getting this error from [rust-analyzer](https://github.com/rust-lang/rust-analyzer) when using `#[derive(ShaderType)]` in VSCode:

```
no method `to_panicvals` on type `StdWrapper<&&str>`
```

<img width="820" alt="screenshot" src="https://user-images.githubusercontent.com/13008492/224143588-c1e4370e-4a76-4622-a801-72f4114d493c.png">

Does anyone know how to fix this?

**Comment by teoxoy** [comment]
Is rustc able to build the project? Also, make sure you have min rust v1.63.
