### ISSUE TITLE
Consider updating `encase_derive_impl` to use `syn@2`

### ISSUE THREAD

**Issue by LikeLakers2** [teoxoy/encase#36]
Hi! I noticed that `encase_derive_impl` (and possibly other parts of this repository) depend on `syn@1`. Perhaps you could consider updating to use `syn@2` wherever possible?

Some things worth noting for anyone who intends to take on this suggestion:
* `syn@2`'s MSRV is Rust 1.56, up from `syn@1`'s Rust 1.31. I am unsure if this may be a problem - the repository's main `Cargo.toml` [specifies a MSRV of Rust 1.63](https://github.com/teoxoy/encase/blob/c48b0beeee882f38c263d63d48f793d232ce9119/Cargo.toml#L5), but `encase_derive` and `encase_derive_impl` do not specify a MSRV.
* Updating to `syn@2` may not be as simple as swapping the version number - there are a number of breaking changes in `syn@2`, listed at <https://github.com/dtolnay/syn/releases/tag/2.0.0>.

If you do consider to transition to `syn@2`, you have my thanks! :)

**Comment by teoxoy** [comment]
See https://github.com/teoxoy/encase/pull/35

**Comment by LikeLakers2** [comment]
Ah, I must've missed that while checking through the repository. My bad!

**Comment by teoxoy** [comment]
No worries! Regarding the MSRV, it's the same for the derive crates as it is for the main lib.
