### ISSUE TITLE
Consider inlining hot functions for primitives, vectors, and matricies

### ISSUE THREAD

**Issue by james7132** [teoxoy/encase#38]
![image](https://user-images.githubusercontent.com/3137680/230850074-9e739487-6345-4a45-93a2-e60f4e7eb4ea.png)

This flamegraph seems to show that many of the potentially hot function calls are not being inlined (i.e. `<f32 as WriteInto>::write_into`). This is potentially very costly in terms of performance.

This also seems to carry over to the internal types like Cursor and many BufferRef/BufferMut implementations as well.

**Comment by teoxoy** [comment]
Inlining is not something I looked into yet. I generally thought the compiler would be smart enough to inline at least `<f32 as WriteInto>::write_into`.

There are some benchmarks in the repo that could help with this.
