### ISSUE TITLE
Wrong min_size() for struct

### ISSUE THREAD

**Issue by JMS55** [teoxoy/encase#64]
```rust
#[derive(ShaderType)]
pub struct GpuSolariMaterial {
    pub base_color: [f32; 4],
    pub emissive: [f32; 4],
    pub base_color_texture_id: u32,
    pub normal_map_texture_id: u32,
    pub emissive_texture_id: u32,
}
```

`GpuSolariMaterial::min_size()` should be 48, but is 44.

**Comment by teoxoy** [comment]
Why should it be 48? (4 * 4) + (4 * 4) + 4 + 4 + 4 = 44; alignment is 4 as well.

**Comment by JMS55** [comment]
Alignment is 16 bytes in storage buffers, as it's the maximal alignment of the member fields, in this case alignof(vec4<f32>) = 16.

**Comment by teoxoy** [comment]
Encase interprets rust arrays as wgsl arrays, so in the struct above the `[f32; 4]` is an array of 4 `f32`s.

**Comment by JMS55** [comment]
Ah that makes sense :sweat_smile:, thanks!
