### ISSUE TITLE
How to Derive `Shadertype` for generic structs without unsafe code?

### ISSUE THREAD

**Issue by davids91** [teoxoy/encase#78]
I have a generic vector implementation: 
```
#[repr(C)]
struct MyVec<T> {
    pub x: T,
    pub y: T,
    pub z: T,
}

pub type MyVecf = MyVec<f32>;
```

but it has `usize` variants so I can not use the `ShaderSize` derive macro ( as far as I know ).

I've tried implementing the `ShaderSize` trait manually but I just can't understand how it operates. I've also tried digging around the repo and supported types for clues, and found the following to seem to work: 

```
use encase::{impl_vector, vector::AsMutVectorParts, vector::AsRefVectorParts};

impl_vector!(3, MyVecf, f32; using From);

impl AsRefVectorParts<f32, 3> for MyVecf {
    fn as_ref_parts(&self) -> &[f32; 3] {
        unsafe { &*(self as *const MyVecf as *const [f32; 3]) }
    }
}

impl AsMutVectorParts<f32, 3> for MyVecf {
    fn as_mut_parts(&mut self) -> &mut [f32; 3] {
        unsafe { &mut *(self as *mut MyVecf as *mut [f32; 3]) }
    }
}
```

but I would really like to avoid using unsafe code, is there any possibility of it?

**Comment by davids91** [comment]
HI, and thank you for the answer! 
In my case one of the concrete implementations involve `T = usize`, so I don't have the possibility to `derive` the struct, rather I'd like to implement the trait for a concrete type `MyVecf`; I managed to do it with the above code, but I was wondering if you have something simpler for that, or a feature in plan? 

I'd like to avoid unsafe code is possible.

**Comment by teoxoy** [comment]
Ah I see, I don't think there is a better way without unsafe.
